/* 
Travis: put the name of the image here, give it a caption if you want, 
and get it's height and width properties by right-clicking and looking at the images 'Properties' on Windows,
or right-clicking and then 'Get Info' on Mac
*/

const slideImages = [
  {
    original: "/DSC00318.jpg",
    thumbnail: "/DSC00318.jpg",
    caption: "",
    originalWidth: 3161,
    originalHeight: 2118,
  },
  {
    original: "/DSC00319.jpg",
    thumbnail: "/DSC00319.jpg",
    caption: "",
    originalWidth: 2806,
    originalHeight: 1849,
  },
  {
    original: "/DSC00335.jpg",
    thumbnail: "/DSC00335.jpg",
    caption: "",
    originalWidth: 2867,
    originalHeight: 2125,
  },
  {
    original: "/DSC00337.jpg",
    thumbnail: "/DSC00337.jpg",
    caption: "",
    originalWidth: 2963,
    originalHeight: 2209,
  },
  {
    original: "/DSC00395.jpg",
    thumbnail: "/DSC00395.jpg",
    caption: "",
    originalWidth: 2823,
    originalHeight: 2220,
  },
  {
    original: "/DSC00416.jpg",
    thumbnail: "/DSC00416.jpg",
    caption: "",
    originalWidth: 3128,
    originalHeight: 3806,
  },
  {
    original: "/DSC00421.jpg",
    thumbnail: "/DSC00421.jpg",
    caption: "",
    originalWidth: 4083,
    originalHeight: 3028,
  },
  {
    original: "/DSC00424.jpg",
    thumbnail: "/DSC00424.jpg",
    caption: "",
    originalWidth: 4326,
    originalHeight: 3179,
  },
  {
    original: "/DSC00452.jpg",
    thumbnail: "/DSC00452.jpg",
    caption: "",
    originalWidth: 2005,
    originalHeight: 2187,
  },
  {
    original: "/DSC00464.jpg",
    thumbnail: "/DSC00464.jpg",
    caption: "",
    originalWidth: 2359,
    originalHeight: 2208,
  },
  {
    original: "/DSC00480.jpg",
    thumbnail: "/DSC00480.jpg",
    caption: "",
    originalWidth: 2820,
    originalHeight: 2201,
  },
  {
    original: "/DSC00323.jpg",
    thumbnail: "/DSC00323.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00327.jpg",
    thumbnail: "/DSC00327.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00328.jpg",
    thumbnail: "/DSC00328.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00326.jpg",
    thumbnail: "/DSC00326.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00330.jpg",
    thumbnail: "/DSC00330.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00331.jpg",
    thumbnail: "/DSC00331.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00332.jpg",
    thumbnail: "/DSC00332.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00334.jpg",
    thumbnail: "/DSC00334.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00336.jpg",
    thumbnail: "/DSC00336.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00340.jpg",
    thumbnail: "/DSC00340.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00345.jpg",
    thumbnail: "/DSC00345.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00349.jpg",
    thumbnail: "/DSC00349.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00352.jpg",
    thumbnail: "/DSC00352.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00355.jpg",
    thumbnail: "/DSC00355.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00356.jpg",
    thumbnail: "/DSC00356.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00357.jpg",
    thumbnail: "/DSC00357.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00369.jpg",
    thumbnail: "/DSC00369.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00370.jpg",
    thumbnail: "/DSC00370.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00371.jpg",
    thumbnail: "/DSC00371.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00373.jpg",
    thumbnail: "/DSC00373.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00374.jpg",
    thumbnail: "/DSC00374.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00378.jpg",
    thumbnail: "/DSC00378.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00381.jpg",
    thumbnail: "/DSC00381.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00382.jpg",
    thumbnail: "/DSC00382.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00387.jpg",
    thumbnail: "/DSC00387.jpg ",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00391.jpg",
    thumbnail: "/DSC00391.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00396.jpg",
    thumbnail: "/DSC00396.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00397.jpg",
    thumbnail: "/DSC00397.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00398.jpg",
    thumbnail: "/DSC00398.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00404.jpg",
    thumbnail: "/DSC00404.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00408.jpg",
    thumbnail: "/DSC00408.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00412.jpg",
    thumbnail: "/DSC00412.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00417.jpg",
    thumbnail: "/DSC00417.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00420.jpg",
    thumbnail: "/DSC00420.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00433.jpg",
    thumbnail: "/DSC00433.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00434.jpg",
    thumbnail: "/DSC00434.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00441.jpg",
    thumbnail: "/DSC00441.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00446.jpg",
    thumbnail: "/DSC00446.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00466.jpg",
    thumbnail: "/DSC00466.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00470.jpg",
    thumbnail: "/DSC00470.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00477.jpg",
    thumbnail: "/DSC00477.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00483.jpg",
    thumbnail: "/DSC00483.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00485.jpg",
    thumbnail: "/DSC00485.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00492.jpg",
    thumbnail: "/DSC00492.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  {
    original: "/DSC00508.jpg",
    thumbnail: "/DSC00508.jpg",
    caption: "",
    // originalWidth: ,
    // originalHeight: ,
  },
  // ... add more images here by copying lines 8-31 above and pasting on line 32.
  // Add as many as you need, just be sure to edit the 'original', 'thumbnail', 'caption', 'originalWidth', and 'originalHeight' properties.
  // Make sure the capitalization of 'jpg' matches that of the image you upload.
  // You can rename or delete the examples above by deleting everything in the 'curly brackets'.
];

export default slideImages;
